name: Create and push Robottelo Container to Quay.io

on:
  push:
    branches: master

jobs:
  robottelo_container:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: publish image to Quay
        uses: docker/build-push-action@v1
        with:
          path: .
          file: ./Dockerfile
          registry: ${{ secrets.REGISTRY_SERVER }}
          repository: ${{ secrets.REGISTRY_NAMESPACE }}/robottelo
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: latest
